[package]
name = "metrics-types"
version = "0.1.0"

edition = "2024"
license-file.workspace = true
publish = false

[dependencies]
models = { path = "../models" }

serde.workspace = true
time.workspace = true

[lints]
workspace = true
