# fly.toml app configuration file generated for quickwit-misty-moon-5123 on 2025-12-01T21:20:45-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'quickwit-misty-moon-5123'
primary_region = 'iad'

[build]
image = 'quickwit/quickwit:latest'

[experimental]
cmd = [ "run" ]

[env]
# Required secrets:
# - AWS_ACCESS_KEY_ID (R2 access key)
# - AWS_SECRET_ACCESS_KEY (R2 secret key)
# - AWS_ENDPOINT_URL (R2 endpoint)
AWS_REGION = 'auto'
QW_CLUSTER_ID = 'quickwit-cluster'
QW_DATA_DIR = '/quickwit/qwdata'
QW_DEFAULT_INDEX_ROOT_URI = 's3://rambit-quickwit/indexes'
QW_LISTEN_ADDRESS = '::'
QW_NODE_ID = 'node-1'

[[mounts]]
destination = '/quickwit/qwdata'
initial_size = '10gb'
source = 'quickwit_data'

[[vm]]
cpu_kind = 'shared'
cpus = 2
memory = '2gb'
