[package]
name = "billing-domain"
version = "0.1.0"

edition = "2024"
license-file.workspace = true
publish = false

[dependencies]
models = { path = "../models" }

miette.workspace = true

paddle-rust-sdk = { version = "0.14" }

[lints]
workspace = true
